[package]
name = "groceries-bmesh"
version = "0.1.0"
description = "A Tauri App"
authors = ["you"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
# The `_lib` suffix may seem redundant but it is necessary
# to make the lib name unique and wouldn't conflict with the bin name.
# This seems to be only an issue on Windows, see https://github.com/rust-lang/cargo/issues/8519
name = "groceries_bmesh_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
# https://github.com/open-source-cooperative/android-native-keyring-store/issues/21
tauri = { version = "=2.11.5", features = [] }
tauri-runtime = { version = "=2.11.3", features = [] }

tauri-plugin-opener = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
groceries-bmesh-core = { path="../groceries-bmesh-core" }
reqwest = { version = "0.13", default-features = false, features = ["blocking", "rustls", "rustls-no-provider"] }
tokio = { version = "1.53.1", default-features = false, features = ["sync", "macros", "rt", "time"] }
tauri-plugin-blew = "0.3.1"
futures = "0.3.33"
