[package]
name = "groceries-bmesh"
version = "0.1.0"
description = "A Tauri App"
authors = ["you"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
# The `_lib` suffix may seem redundant but it is necessary
# to make the lib name unique and wouldn't conflict with the bin name.
# This seems to be only an issue on Windows, see https://github.com/rust-lang/cargo/issues/8519
name = "groceries_bmesh_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
# waiting for the new release (probably 2.12)
# https://github.com/open-source-cooperative/android-native-keyring-store/issues/21
tauri = { git = "https://github.com/tauri-apps/tauri/", features = [] }
# tauri-runtime = { git = "https://github.com/tauri-apps/tauri/" }
# tauri = { version = "=2.11.5", features = [] }
# tauri-runtime = { version = "=2.11.3", features = [] }

reqwest = { version = "0.13", default-features = false, features = ["blocking", "rustls", "rustls-no-provider"] }
groceries-bmesh-core = { path="../groceries-bmesh-core" }
# tauri-plugin-blew = "0.3.1"
